--- Central hotkey registry used by command-palette and service integrations.

---@class BindingSpec
---@field group string Command-palette category.
---@field title string Human-readable action name.
---@field modifiers string[] Hammerspoon modifier names.
---@field key string Trigger key.
---@field action fun() Callback invoked by the binding.
---@field shortcut? string Display label generated by `bind`.
---@field hotkey? hs.hotkey Registered Hammerspoon hotkey.
---@field hidden? boolean Exclude the action from the command palette.
---@field apps? string[] Application names or bundle IDs where this action is relevant.
---@field workspaces? string[] AeroSpace workspaces where this action is relevant.
---@field keywords? string[] Additional command-palette search terms.
---@field priority? integer Base command-palette ranking.

---@class BindingContext
---@field app? string Frontmost application name.
---@field bundleID? string Frontmost application bundle ID.
---@field workspace? string Focused AeroSpace workspace.

local M = {}

---@type BindingSpec[]
local actions = {}

local modifierNames = {
    alt = "⌥",
    cmd = "⌘",
    ctrl = "⌃",
    shift = "⇧",
}

--- Matches a context value against case-insensitive action metadata.
---@param values? string[]
---@param candidates string[]
---@return boolean
local function matchesAny(values, candidates)
    if not values then
        return false
    end

    for _, value in ipairs(values) do
        local normalizedValue = value:lower()
        for _, candidate in ipairs(candidates) do
            if candidate ~= "" and normalizedValue == candidate:lower() then
                return true
            end
        end
    end

    return false
end

--- Formats modifiers and a key as a compact macOS shortcut label.
---@param modifiers string[]
---@param key string
---@return string
local function shortcutLabel(modifiers, key)
    local labels = {}
    for _, modifier in ipairs(modifiers) do
        labels[#labels + 1] = modifierNames[modifier] or modifier
    end
    labels[#labels + 1] = key
    return table.concat(labels)
end

--- Registers an action without creating a keyboard shortcut.
---@param spec BindingSpec
---@return BindingSpec
function M.register(spec)
    actions[#actions + 1] = spec
    return spec
end

--- Creates a hotkey and registers it for discovery.
---@param spec BindingSpec
---@return hs.hotkey
function M.bind(spec)
    spec.shortcut = shortcutLabel(spec.modifiers, spec.key)
    spec.hotkey = hs.hotkey.bind(spec.modifiers, spec.key, spec.action)
    M.register(spec)
    return spec.hotkey
end

--- Scores an action against the active desktop context.
---@param action BindingSpec
---@param context? BindingContext
---@return integer score
---@return string[] matches
function M.contextScore(action, context)
    context = context or {}
    local score = action.priority or 0
    local matches = {}

    if matchesAny(action.apps, { context.app or "", context.bundleID or "" }) then
        score = score + 100
        matches[#matches + 1] = "Current app"
    end

    if matchesAny(action.workspaces, { context.workspace or "" }) then
        score = score + 60
        matches[#matches + 1] = "Workspace " .. context.workspace
    end

    return score, matches
end

--- Returns visible actions sorted by group and title.
---@return BindingSpec[]
function M.actions()
    local visible = {}
    for _, action in ipairs(actions) do
        if not action.hidden then
            visible[#visible + 1] = action
        end
    end

    table.sort(visible, function(left, right)
        if left.group == right.group then
            return left.title < right.title
        end
        return left.group < right.group
    end)

    return visible
end

return M
