--- Central hotkey registry used by command-palette and service integrations.

---@class BindingSpec
---@field group string Command-palette category.
---@field title string Human-readable action name.
---@field modifiers string[] Hammerspoon modifier names.
---@field key string Trigger key.
---@field action fun() Callback invoked by the binding.
---@field shortcut? string Display label generated by `bind`.
---@field hotkey? hs.hotkey Registered Hammerspoon hotkey.
---@field hidden? boolean Exclude the action from the command palette.

local M = {}

---@type BindingSpec[]
local actions = {}

local modifierNames = {
    alt = "⌥",
    cmd = "⌘",
    ctrl = "⌃",
    shift = "⇧",
}

--- Formats modifiers and a key as a compact macOS shortcut label.
---@param modifiers string[]
---@param key string
---@return string
local function shortcutLabel(modifiers, key)
    local labels = {}
    for _, modifier in ipairs(modifiers) do
        labels[#labels + 1] = modifierNames[modifier] or modifier
    end
    labels[#labels + 1] = key
    return table.concat(labels)
end

--- Registers an action without creating a keyboard shortcut.
---@param spec BindingSpec
---@return BindingSpec
function M.register(spec)
    actions[#actions + 1] = spec
    return spec
end

--- Creates a hotkey and registers it for discovery.
---@param spec BindingSpec
---@return hs.hotkey
function M.bind(spec)
    spec.shortcut = shortcutLabel(spec.modifiers, spec.key)
    spec.hotkey = hs.hotkey.bind(spec.modifiers, spec.key, spec.action)
    M.register(spec)
    return spec.hotkey
end

--- Returns visible actions sorted by group and title.
---@return BindingSpec[]
function M.actions()
    local visible = {}
    for _, action in ipairs(actions) do
        if not action.hidden then
            visible[#visible + 1] = action
        end
    end

    table.sort(visible, function(left, right)
        if left.group == right.group then
            return left.title < right.title
        end
        return left.group < right.group
    end)

    return visible
end

return M
